import Link from "next/link";
import { Alert, Card, DatabaseUnavailable, PageHeader, buttonClass, fieldClass, secondaryButtonClass } from "@/components/commerce/AdminUI";
import { formatBusinessDate } from "@/lib/commerce/dates";
import { formatCurrency } from "@/lib/commerce/finance";
import { listInventory, listSuppliers } from "@/lib/commerce/repository";

export const dynamic = "force-dynamic";

export default async function InventoryPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const notice = await searchParams;
  const data = await Promise.all([listInventory(), listSuppliers()]).catch(() => null);
  if (!data) return <><PageHeader title="Inventory & purchases" /><DatabaseUnavailable /></>;
  const [{ products, lots, movements }, suppliers] = data;
  return (
      <>
        <PageHeader title="Inventory & purchases" description="On-hand stock is calculated from the movement ledger. Costed purchase lots retain the historical landed cost used for FIFO COGS." actions={<><a href="/api/admin/commerce/exports/inventory" className={secondaryButtonClass}>Export inventory</a><a href="/api/admin/commerce/exports/lots" className={secondaryButtonClass}>Export purchase lots</a></>} />
        <div className="mb-5 space-y-3">{notice.saved && <Alert tone="success">Inventory data saved.</Alert>}{notice.error && <Alert tone="error">The change was not saved. Review the values and try again.</Alert>}</div>
        <Card className="overflow-hidden">
          <div className="border-b border-slate-200 p-5"><h2 className="text-lg font-extrabold text-[#0c2f4a]">Current inventory</h2><p className="mt-1 text-xs text-slate-500">Available equals on hand today; reservations are not enabled.</p></div>
          <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Product</th><th className="px-4 py-3">SKU</th><th className="px-4 py-3">On hand</th><th className="px-4 py-3">Available</th><th className="px-4 py-3">Inventory value</th><th className="px-4 py-3">Low stock</th></tr></thead><tbody>{products.map((product) => {
            const low = product.low_stock_threshold !== null && product.inventory_on_hand <= product.low_stock_threshold;
            return <tr key={product.id} className="border-t border-slate-100"><td className="px-4 py-3"><Link href={`/admin/commerce/products/${product.id}`} className="font-extrabold text-[#0c2f4a] underline">{product.name}</Link></td><td className="px-4 py-3 font-mono text-xs">{product.sku}</td><td className="px-4 py-3 font-bold">{product.inventory_on_hand}</td><td className="px-4 py-3">{product.inventory_on_hand}</td><td className="px-4 py-3">{formatCurrency(product.inventory_value_cents)}</td><td className="px-4 py-3">{product.low_stock_threshold === null ? "Threshold not set" : low ? <span className="font-bold text-red-700">Low</span> : "OK"}</td></tr>;
          })}</tbody></table></div>
        </Card>

        <Card className="mt-6 overflow-hidden">
          <div className="border-b border-slate-200 p-5"><h2 className="text-lg font-extrabold text-[#0c2f4a]">Purchase lots</h2><p className="mt-1 text-xs text-slate-500">Each received batch keeps its supplier, purchase timing, remaining units, and landed unit cost.</p></div>
          <div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Purchase / received</th><th className="px-4 py-3">Product</th><th className="px-4 py-3">Supplier</th><th className="px-4 py-3">Order / lot</th><th className="px-4 py-3">Purchased</th><th className="px-4 py-3">Remaining</th><th className="px-4 py-3">Unit purchase</th><th className="px-4 py-3">Landed unit</th><th className="px-4 py-3">Strategy</th><th className="px-4 py-3">Location</th></tr></thead><tbody>{lots.length ? lots.map((lot) => <tr key={String(lot.id)} className="border-t border-slate-100"><td className="whitespace-nowrap px-4 py-3">{lot.purchased_at ? formatBusinessDate(String(lot.purchased_at)) : "Purchase unknown"}<br /><span className="text-xs text-slate-500">Received {formatBusinessDate(String(lot.received_at))}</span></td><td className="px-4 py-3 font-bold">{String(lot.product_name)}</td><td className="px-4 py-3">{String(lot.supplier_name || "Not recorded")}</td><td className="px-4 py-3">{String(lot.supplier_order_number || lot.reference || lot.id)}</td><td className="px-4 py-3">{String(lot.quantity_purchased || lot.quantity_received)}</td><td className="px-4 py-3 font-bold">{String(lot.quantity_remaining)}</td><td className="px-4 py-3">{formatCurrency(Number(lot.unit_purchase_cost_cents))}</td><td className="px-4 py-3 font-bold">{formatCurrency(Number(lot.landed_unit_cost_cents))}</td><td className="px-4 py-3 capitalize">{String(lot.fulfillment_strategy).replaceAll("_", " ")}</td><td className="px-4 py-3">{String(lot.location)}</td></tr>) : <tr><td colSpan={10} className="px-4 py-12 text-center text-slate-500"><p className="font-bold text-slate-700">No purchase lots yet</p><p className="mt-1">Add the first real SideKick purchase below. Current stock is intentionally not inferred from storefront availability.</p></td></tr>}</tbody></table></div>
        </Card>

        <Card className="mt-6 overflow-hidden">
          <div className="border-b border-slate-200 p-5"><h2 className="text-lg font-extrabold text-[#0c2f4a]">Recent inventory movements</h2><p className="mt-1 text-xs text-slate-500">Receipts, sales, and corrections are recorded in the inventory ledger. The newest 100 entries appear here.</p></div>
          <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Date</th><th className="px-4 py-3">Product</th><th className="px-4 py-3">Change</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Order / lot</th><th className="px-4 py-3">Reason</th></tr></thead><tbody>{movements.length ? movements.map((movement) => {
            const quantity = Number(movement.quantity_delta);
            const reference = movement.order_number || movement.supplier_order_number || movement.lot_reference || "—";
            return <tr key={String(movement.id)} className="border-t border-slate-100"><td className="whitespace-nowrap px-4 py-3">{formatBusinessDate(String(movement.occurred_at), true)}</td><td className="px-4 py-3"><p className="font-bold">{String(movement.product_name)}</p><p className="font-mono text-xs text-slate-500">{String(movement.sku)}</p></td><td className={`px-4 py-3 font-extrabold ${quantity > 0 ? "text-emerald-700" : "text-red-700"}`}>{quantity > 0 ? `+${quantity}` : quantity}</td><td className="px-4 py-3 capitalize">{String(movement.movement_type).replaceAll("_", " ")}</td><td className="px-4 py-3">{String(reference)}</td><td className="px-4 py-3">{String(movement.reason || "—")}</td></tr>;
          }) : <tr><td colSpan={6} className="px-4 py-10 text-center text-slate-500">No inventory movements yet. Receiving the first real purchase lot will create the opening ledger entry.</td></tr>}</tbody></table></div>
        </Card>

        <div className="mt-6 grid gap-6 xl:grid-cols-2">
          <Card className="p-5" id="add-lot"><h2 className="text-lg font-extrabold text-[#0c2f4a]">Add a purchase lot</h2><p className="mt-1 text-sm text-slate-600">Use real supplier and cost facts only. Outbound customer shipping belongs on the order, not here.</p><form action="/api/admin/commerce/inventory/lots" method="post" className="mt-5 grid gap-4 sm:grid-cols-2">
            <label className="text-sm font-bold">Product<select name="productId" className={`${fieldClass} mt-1`} required>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label className="text-sm font-bold">Supplier<select name="supplierId" className={`${fieldClass} mt-1`}><option value="">Not recorded</option>{suppliers.map((supplier) => <option key={String(supplier.id)} value={String(supplier.id)}>{String(supplier.name)}</option>)}</select></label>
            <label className="text-sm font-bold">Supplier order number<input name="supplierOrderNumber" className={`${fieldClass} mt-1`} /></label><label className="text-sm font-bold">Owner lot reference<input name="reference" className={`${fieldClass} mt-1`} /></label>
            <label className="text-sm font-bold sm:col-span-2">Supplier product URL<input name="supplierProductUrl" type="url" className={`${fieldClass} mt-1`} /></label>
            <label className="text-sm font-bold">Purchase date<input name="purchasedAt" type="date" className={`${fieldClass} mt-1`} /></label><label className="text-sm font-bold">Expected arrival<input name="expectedArrivalAt" type="date" className={`${fieldClass} mt-1`} /></label><label className="text-sm font-bold">Received date<input name="receivedAt" type="date" className={`${fieldClass} mt-1`} required /></label>
            <label className="text-sm font-bold">Quantity purchased<input name="quantityPurchased" type="number" min="1" className={`${fieldClass} mt-1`} /></label><label className="text-sm font-bold">Usable quantity received<input name="quantityReceived" type="number" min="1" className={`${fieldClass} mt-1`} required /></label>
            <label className="text-sm font-bold">Unit purchase price ($)<input name="unitPurchaseCost" inputMode="decimal" className={`${fieldClass} mt-1`} required /></label><label className="text-sm font-bold">Inbound supplier shipping ($)<input name="inboundShipping" inputMode="decimal" defaultValue="0.00" className={`${fieldClass} mt-1`} /></label>
            <label className="text-sm font-bold">Duties / import costs ($)<input name="dutyAndFees" inputMode="decimal" defaultValue="0.00" className={`${fieldClass} mt-1`} /></label><label className="text-sm font-bold">Other landed costs ($)<input name="otherLandedCosts" inputMode="decimal" defaultValue="0.00" className={`${fieldClass} mt-1`} /></label>
            <label className="text-sm font-bold">Strategy<select name="fulfillmentStrategy" className={`${fieldClass} mt-1`}><option value="stocked_local">Sent to me first</option><option value="dropship">Dropshipped to customer</option><option value="third_party_fulfillment">Third-party fulfillment</option><option value="other">Other</option></select></label><label className="text-sm font-bold">Location<input name="location" defaultValue="Admiral inventory" className={`${fieldClass} mt-1`} /></label>
            <label className="text-sm font-bold sm:col-span-2">Notes<textarea name="notes" rows={3} className={`${fieldClass} mt-1`} /></label><div className="sm:col-span-2"><button className={buttonClass}>Save purchase lot</button></div>
          </form></Card>

          <div className="space-y-6">
            <Card className="p-5"><h2 className="text-lg font-extrabold text-[#0c2f4a]">Inventory correction</h2><p className="mt-1 text-sm text-slate-600">Manual changes require a reason and are written to the ledger. Negative corrections consume costed lots FIFO when available.</p><form action="/api/admin/commerce/inventory/adjustments" method="post" className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Product<select name="productId" className={`${fieldClass} mt-1`}>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><label className="text-sm font-bold">Quantity change<input name="quantityDelta" type="number" placeholder="Example: -1 or 3" className={`${fieldClass} mt-1`} required /></label><label className="text-sm font-bold sm:col-span-2">Reason<input name="reason" placeholder="Damaged, lost, sample, physical count correction…" className={`${fieldClass} mt-1`} required /></label><div className="sm:col-span-2"><button className={buttonClass}>Record correction</button></div></form></Card>
            <Card className="p-5"><h2 className="text-lg font-extrabold text-[#0c2f4a]">Suppliers</h2>{suppliers.length ? <ul className="mt-4 divide-y divide-slate-100">{suppliers.map((supplier) => <li key={String(supplier.id)} className="py-3 text-sm"><strong>{String(supplier.name)}</strong><span className="ml-2 text-slate-500">{String(supplier.platform || "Platform not recorded")} · {String(supplier.lot_count)} lot(s)</span></li>)}</ul> : <p className="mt-3 text-sm text-slate-500">No suppliers yet.</p>}<form action="/api/admin/commerce/suppliers" method="post" className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Supplier name<input name="name" className={`${fieldClass} mt-1`} required /></label><label className="text-sm font-bold">Platform<input name="platform" placeholder="AliExpress, manufacturer…" className={`${fieldClass} mt-1`} /></label><label className="text-sm font-bold sm:col-span-2">Vendor URL<input name="websiteUrl" type="url" className={`${fieldClass} mt-1`} /></label><label className="text-sm font-bold">Contact name<input name="contactName" className={`${fieldClass} mt-1`} /></label><label className="text-sm font-bold">Email<input name="email" type="email" className={`${fieldClass} mt-1`} /></label><label className="text-sm font-bold sm:col-span-2">Notes<textarea name="notes" rows={2} className={`${fieldClass} mt-1`} /></label><div className="sm:col-span-2"><button className={buttonClass}>Add supplier</button></div></form></Card>
          </div>
        </div>
      </>
  );
}
